#!/usr/bin/env bash

#
# #########################
# Purpose: Clone a case for PPE
# Author: Adrianna C. Foster
# Date: April, 2022
# bash version 4.2.46
# #########################
# #########################

SAMPLE=$1

## create file and folder names
NAME=FATES_NOCOMP_FBG_PPE_spbase_nudged_intmaxmin${SAMPLE}


## clone dir
## these won't change
CASE_DIR=/glade/work/rfisher/FATES_calibration/FATES_NOCOMP_OAAT/ensemble_cases
SRCDIR=/glade/work/rfisher/FATES_calibration/CTSM_calib_branch

## output directory
OUT_DIR=/glade/scratch/rfisher

## Cime scripts directory
base_dir=${SRCDIR}/cime/scripts

## full path of case
case_name=${CASE_DIR}/${NAME}

## clone from the base case
cd ${base_dir}
cd ${case_name}

## these options are reset in the clone
./xmlchange --id STOP_N --val 10
./xmlchange --id STOP_OPTION --val nyears
./xmlchange --id REST_OPTION --val nyears
./xmlchange --id RESUBMIT --val 6
./xmlchange --id JOB_WALLCLOCK_TIME --val 05:00:00 --subgroup case.run
#./xmlchange --id JOB_QUEUE --val economy --subgroup case.run
./xmlchange --id CONTINUE_RUN --val FALSE

## submit the case - no need to build
./case.submit
